import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import { TanstackProvider } from "@/shared/providers/TanstackProvider";
import { TooltipProvider } from "@/shared/ui/tooltip";
import { BaseLayout } from "@/widgets/Layout";
import "./globals.css";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dmSans.variable} antialiased`}>
        <TanstackProvider>
          <TooltipProvider>
            <BaseLayout>{children}</BaseLayout>
          </TooltipProvider>
        </TanstackProvider>
      </body>
    </html>
  );
}
